
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else   /* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif   /* defined (__STDC__) */
#endif   /* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
   do \
      { \
      /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
      *yy_cp = (yy_hold_char); \
      YY_RESTORE_YY_MORE_OFFSET \
      (yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
      YY_DO_BEFORE_ACTION; /* set up yytext again */ \
      } \
   while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
   {
   FILE *yy_input_file;

   char *yy_ch_buf;      /* input buffer */
   char *yy_buf_pos;      /* current position in input buffer */

   /* Size of input buffer in bytes, not including room for EOB
    * characters.
    */
   yy_size_t yy_buf_size;

   /* Number of characters read into yy_ch_buf, not including EOB
    * characters.
    */
   int yy_n_chars;

   /* Whether we "own" the buffer - i.e., we know we created it,
    * and can realloc() it to grow it, and should free() it to
    * delete it.
    */
   int yy_is_our_buffer;

   /* Whether this is an "interactive" input source; if so, and
    * if we're using stdio for input, then we want to use getc()
    * instead of fread(), to make sure we stop fetching input after
    * each newline.
    */
   int yy_is_interactive;

   /* Whether we're considered to be at the beginning of a line.
    * If so, '^' rules will be active on the next match, otherwise
    * not.
    */
   int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
   /* Whether to try to fill the input buffer when we reach the
    * end of it.
    */
   int yy_fill_buffer;

   int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
   /* When an EOF's been seen but there's still some text to process
    * then we mark the buffer as YY_EOF_PENDING, to indicate that we
    * shouldn't try reading from the input source any more.  We might
    * still have a bunch of tokens to match, though, because of
    * possible backing-up.
    *
    * When we actually see the EOF, we change the status to "new"
    * (via yyrestart()), so that the user can continue scanning by
    * just pointing yyin at a new input file.
    */
#define YY_BUFFER_EOF_PENDING 2

   };
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;      /* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;      /* whether we need to initialize */
static int yy_start = 0;   /* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
   { \
   if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
      YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
   } \
   YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
   }

#define yy_set_bol(at_bol) \
   { \
   if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
      YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
   } \
   YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
   }

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
   (yytext_ptr) = yy_bp; \
   yyleng = (size_t) (yy_cp - yy_bp); \
   (yy_hold_char) = *yy_cp; \
   *yy_cp = '\0'; \
   (yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 105
#define YY_END_OF_BUFFER 106
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
   {
   flex_int32_t yy_verify;
   flex_int32_t yy_nxt;
   };
static yyconst flex_int16_t yy_accept[339] =
    {   0,
        0,    0,  106,  104,  103,  103,   91,  104,   97,   90,
      104,   85,   86,   95,   94,   82,   93,   89,   96,   51,
       51,   83,   79,   98,   84,   99,  102,   48,   48,   87,
       88,  100,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   80,  101,
       81,   92,   78,    0,   56,    0,   64,   81,   73,   65,
        0,    0,   62,   70,   60,   71,   61,   72,    0,   54,
        1,    2,   63,   55,   50,    0,   51,    0,   51,   88,
       80,   87,   69,   75,   77,   76,   68,   48,    0,    0,
       66,   48,   48,   48,   48,   48,   48,   48,   48,   48,

       48,   16,   48,   48,   48,   48,   48,   48,   48,   24,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   67,   74,   52,   57,    0,   54,    2,   54,
        0,   55,   50,    0,   53,   49,   59,   58,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   22,   48,
       48,   27,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,    0,
       54,    0,   54,    0,   55,   53,   49,   48,   48,   48,
       48,   48,   48,   48,   48,   48,    7,   48,   10,   11,

       48,   48,   48,   48,   18,   19,   48,   48,   48,   23,
       48,   28,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   46,   48,   48,   48,   43,   48,   48,    0,   54,
        8,   48,   48,   48,   48,   48,   48,   48,   48,    9,
       13,   48,   48,   48,   48,   47,   21,   48,   48,   48,
       48,   33,   48,   48,   48,   48,   48,   48,   41,   48,
       48,   45,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   17,   20,   26,   48,   48,   32,   35,   36,
       37,   38,   39,   48,   48,   48,   48,   48,   48,   48,
        6,   48,   48,   48,   48,   15,   48,   48,   40,   48,

       48,   12,   48,    0,   48,    5,   48,   48,   48,   48,
       14,   29,   30,   42,   44,   48,   48,   48,   48,   48,
       25,   48,   48,   31,   34,   48,   48,   48,   48,   48,
       48,    0,   48,    4,    0,   48,    3,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,    1,   25,   26,   27,   25,   28,   29,
       30,   30,   31,   30,   30,   32,   30,   30,   30,   30,
       30,   30,   30,   30,   33,   30,   30,   34,   30,   30,
       35,   36,   37,   38,   39,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   30,   49,   50,   51,   52,
       53,   54,   30,   55,   56,   57,   58,   59,   60,   61,
       62,   63,   64,   65,   66,   67,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[68] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    1,    1,    4,    4,    1,    1,
        1,    1,    1,    1,    4,    4,    4,    4,    4,    5,
        5,    5,    5,    5,    1,    1,    1,    1,    5,    4,
        4,    4,    4,    4,    4,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[347] =
    {   0,
        0,    0,  686,  687,  687,  687,  663,   63,   47,   64,
      648,  687,  687,  661,   60,  687,   61,   59,   69,   85,
       78,  659,  687,   86,  659,   56,  687,    0,   82,  687,
      687,  658,   94,  621,  623,   41,   45,   62,   84,  624,
       52,  623,  631,   84,   54,  622,  620,  625,  687,   93,
      687,  687,  687,  121,  687,  668,  687,  687,  687,  687,
       65,  137,  687,  687,  687,  687,  687,  687,  655,  121,
      687,    0,  687,  144,  152,  142,  142,    0,  180,  687,
      687,  687,  647,  687,  687,  687,  646,    0,  142,  631,
      687,  613,  612,  613,  159,  606,  618,  605,  620,  607,

      613,  599,  600,  597,  597,  603,  599,  596,  593,    0,
       98,  597,  160,  595,  105,   87,  599,  588,  591,  131,
      133,  596,  687,  687,  687,  687,  208,  687,    0,  211,
      219,  687,  202,  146,  230,  213,  687,  687,  590,  591,
      601,  134,  587,  578,  594,  589,  583,  595,  590,  578,
      148,  592,  590,  586,  578,  584,  571,  586,    0,  572,
      576,    0,  577,  574,  564,  562,  564,  566,  573,  559,
      557,  557,  569,  568,  558,  562,  566,  568,  557,  201,
      236,  252,  687,  224,  255,  687,  244,  556,  551,  558,
      552,  545,  549,  543,  543,  552,    0,  548,    0,    0,

      539,  547,  536,  543,    0,    0,  537,  547,  533,    0,
      537,    0,  532,  532,  531,  528,  540,  530,  534,  539,
      538,    0,  536,  526,  531,    0,  519,  531,  232,  261,
        0,  524,  525,  533,  516,  514,  525,  511,  515,    0,
        0,  514,  515,  520,  511,    0,    0,  518,  504,  512,
      507,    0,  515,  512,  514,  498,  507,  509,    0,  500,
      503,    0,  506,  497,  509,  499,  489,  493,  471,  476,
      252,  252,    0,    0,    0,  264,  265,    0,    0,    0,
        0,    0,    0,  259,  259,  251,  238,  258,  311,  256,
        0,  240,  247,  249,  247,    0,  234,  231,    0,  242,

      239,    0,  227,  254,    0,  687,  209,  210,  215,  212,
        0,    0,    0,    0,    0,  182,  175,  174,  166,  182,
        0,  167,  157,    0,    0,  168,  154,  147,  143,  378,
      445,  157,    0,  687,  132,    0,  687,  687,  512,  517,
      519,  524,  126,  529,  534,  539
    } ;

static yyconst flex_int16_t yy_def[347] =
    {   0,
      338,    1,  338,  338,  338,  338,  338,  339,  338,  338,
      340,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  341,  341,  338,
      338,  338,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  338,  338,
      338,  338,  338,  339,  338,  339,  338,  338,  338,  338,
      340,  340,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  342,  338,  338,  338,  338,  338,  343,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  341,  339,  340,
      338,  341,  341,  341,  341,  341,  341,  341,  341,  341,

      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  338,  338,  338,  338,  338,  338,  342,  338,
      338,  338,  338,  338,  338,  343,  338,  338,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  338,
      338,  338,  338,  338,  338,  338,  338,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,

      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  338,  338,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  338,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,

      341,  341,  341,  344,  289,  338,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  338,
      338,  345,  330,  338,  346,  331,  338,    0,  338,  338,
      338,  338,  338,  338,  338,  338
    } ;

static yyconst flex_int16_t yy_nxt[755] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   28,   28,   28,   28,   28,
       28,   29,   28,   28,   30,    4,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   28,   41,   28,   42,
       28,   28,   28,   28,   43,   44,   45,   46,   47,   48,
       28,   28,   28,   49,   50,   51,   52,   55,   57,   58,
       59,   64,  125,   69,   66,   70,   70,   86,   87,   71,
       98,   65,   67,   68,   72,   60,   89,   99,  101,   90,
       73,   81,   74,  100,   79,   79,  110,  102,   56,   74,

       62,   75,   75,  111,   82,   76,   83,   84,  118,   77,
       77,  103,   76,  104,  123,  119,   77,   77,   78,   92,
       93,   76,  105,  106,   94,   55,  170,   77,   76,  136,
      114,  115,   95,  107,   77,   77,  108,   70,   70,  338,
      116,  171,   77,  117,   61,   78,   55,  161,  127,  128,
      168,  337,  128,  134,  162,  134,   56,  124,  135,  135,
      130,  130,  135,  135,  127,  128,   74,  169,   75,   75,
      128,  131,  132,   77,   77,  132,  334,   56,  175,   76,
      177,  331,  178,  133,  133,  330,  176,  131,  132,  191,
      192,   77,  329,  132,   74,   76,   79,   79,  142,   77,

      143,  133,  144,  201,  202,  164,  328,   76,  327,  133,
      326,   77,   77,  145,  146,  165,  166,  181,  181,  180,
      325,  180,  324,   76,  181,  181,  323,  130,  130,   77,
      184,  322,  184,  133,  133,  185,  185,   77,  182,  183,
      185,  185,  183,  321,  187,  187,  135,  135,  230,  230,
      320,  133,  181,  181,  182,  183,  319,  318,  186,  133,
      183,  186,  187,  229,  128,  229,  317,  128,  230,  230,
      187,  185,  185,  306,  186,  187,  187,  230,  230,  186,
      128,  316,  315,  132,  314,  128,  132,  313,  312,  183,
      311,  310,  183,  187,  309,  308,  307,  303,  302,  132,

      301,  187,  300,  299,  132,  183,  298,  297,  296,  295,
      183,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  305,  305,  304,
      306,  304,  304,  304,  304,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  304,  304,  304,  304,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  304,  304,  304,  304,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  333,  333,  332,  334,  332,  332,

      332,  332,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  332,  332,  332,  332,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  332,  332,  332,  332,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  336,  336,  335,  337,  335,  335,  335,  335,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  335,
      335,  335,  335,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,

      336,  336,  336,  336,  336,  336,  336,  336,  335,  335,
      335,  335,   54,   54,   54,   54,   54,   61,   61,  294,
       61,   61,   88,   88,  129,  293,  129,  129,  129,  304,
      304,  304,  304,  304,  332,  332,  332,  332,  332,  335,
      335,  335,  335,  335,  292,  291,  290,  289,  288,  287,
      286,  285,  284,  283,  282,  281,  280,  279,  278,  277,
      276,  275,  274,  273,  272,  271,  270,  269,  268,  267,
      266,  265,  264,  263,  262,  261,  260,  259,  258,  257,
      256,  255,  254,  253,  252,  251,  250,  249,  248,  247,
      246,  245,  244,  243,  242,  241,  240,  239,  238,  237,

      236,  235,  234,  233,  232,  231,  228,  227,  226,  225,
      224,  223,  222,  221,  220,  219,  218,  217,  216,  215,
      214,  213,  212,  211,  210,  209,  208,  207,  206,  205,
      204,  203,  200,  199,  198,  197,  196,  195,  194,  193,
      190,  189,  188,  179,  174,  173,  172,  167,  163,  160,
      159,  158,  157,  156,  155,  154,  153,  152,  151,  150,
      149,  148,  147,  141,  140,  139,   62,  138,  137,  126,
      338,  122,  121,  120,  113,  112,  109,   97,   96,   91,
       85,   80,   63,   62,   53,  338,    3,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,

      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338
    } ;

static yyconst flex_int16_t yy_chk[755] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    8,    9,    9,
       10,   15,   61,   18,   17,   18,   18,   26,   26,   19,
       36,   15,   17,   17,   19,   10,   29,   36,   37,   29,
       19,   24,   21,   36,   21,   21,   41,   37,    8,   20,

       61,   20,   20,   41,   24,   21,   24,   24,   45,   21,
       21,   38,   20,   38,   50,   45,   20,   20,   20,   33,
       33,   21,   38,   39,   33,   54,  116,   21,   20,  343,
       44,   44,   33,   39,   20,   21,   39,   70,   70,   62,
       44,  116,   20,   44,   62,   20,   89,  111,   70,   70,
      115,  335,   70,   76,  111,   76,   54,   50,   76,   76,
       74,   74,  134,  134,   70,   70,   75,  115,   75,   75,
       70,   74,   74,   77,   77,   74,  332,   89,  120,   75,
      121,  329,  121,   75,   75,  328,  120,   74,   74,  142,
      142,   77,  327,   74,   79,   75,   79,   79,   95,   77,

       95,   75,   95,  151,  151,  113,  326,   79,  323,   75,
      322,   79,   79,   95,   95,  113,  113,  180,  180,  127,
      320,  127,  319,   79,  127,  127,  318,  130,  130,   79,
      131,  317,  131,  133,  133,  131,  131,   79,  130,  130,
      184,  184,  130,  316,  136,  136,  135,  135,  229,  229,
      310,  133,  181,  181,  130,  130,  309,  308,  135,  133,
      130,  135,  136,  182,  181,  182,  307,  181,  182,  182,
      136,  185,  185,  304,  135,  187,  187,  230,  230,  135,
      181,  303,  301,  185,  300,  181,  185,  298,  297,  230,
      295,  294,  230,  187,  293,  292,  290,  288,  287,  185,

      286,  187,  285,  284,  185,  230,  277,  276,  272,  271,
      230,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,

      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,

      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  339,  339,  339,  339,  339,  340,  340,  270,
      340,  340,  341,  341,  342,  269,  342,  342,  342,  344,
      344,  344,  344,  344,  345,  345,  345,  345,  345,  346,
      346,  346,  346,  346,  268,  267,  266,  265,  264,  263,
      261,  260,  258,  257,  256,  255,  254,  253,  251,  250,
      249,  248,  245,  244,  243,  242,  239,  238,  237,  236,
      235,  234,  233,  232,  228,  227,  225,  224,  223,  221,
      220,  219,  218,  217,  216,  215,  214,  213,  211,  209,
      208,  207,  204,  203,  202,  201,  198,  196,  195,  194,

      193,  192,  191,  190,  189,  188,  179,  178,  177,  176,
      175,  174,  173,  172,  171,  170,  169,  168,  167,  166,
      165,  164,  163,  161,  160,  158,  157,  156,  155,  154,
      153,  152,  150,  149,  148,  147,  146,  145,  144,  143,
      141,  140,  139,  122,  119,  118,  117,  114,  112,  109,
      108,  107,  106,  105,  104,  103,  102,  101,  100,   99,
       98,   97,   96,   94,   93,   92,   90,   87,   83,   69,
       56,   48,   47,   46,   43,   42,   40,   35,   34,   32,
       25,   22,   14,   11,    7,    3,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,

      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "ADaAn_Lexer.l"
#line 2 "ADaAn_Lexer.l"
/***************************************************************************
 *   Copyright (C) 2007 by Marouane Belaoucha   *
 *   bem@prism.uvsq.fr   *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU Lesser General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/

//#include <string.h>   /* for strcmp, strdup & friends */
//#include <stdio.h>   /* for strcmp, strdup & friends */
//#include <stdlib.h>   /* for atoi() */
#include "ADaAn_Parser.hh"

#define YY_NO_UNISTD_H

int parser_line;
int parser_col;

extern int (*fct)(char*);


#line 763 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
   if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
      { \
      int c = '*'; \
      unsigned n; \
      for ( n = 0; n < max_size && \
              (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
         buf[n] = (char) c; \
      if ( c == '\n' ) \
         buf[n++] = (char) c; \
      if ( c == EOF && ferror( yyin ) ) \
         YY_FATAL_ERROR( "input in flex scanner failed" ); \
      result = n; \
      } \
   else \
      { \
      errno=0; \
      while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
         { \
         if( errno != EINTR) \
            { \
            YY_FATAL_ERROR( "input in flex scanner failed" ); \
            break; \
            } \
         errno=0; \
         clearerr(yyin); \
         } \
      }\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
   YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
   register yy_state_type yy_current_state;
   register char *yy_cp, *yy_bp;
   register int yy_act;
    
#line 47 "ADaAn_Lexer.l"

#line 947 "lex.yy.c"

   if ( !(yy_init) )
      {
      (yy_init) = 1;

#ifdef YY_USER_INIT
      YY_USER_INIT;
#endif

      if ( ! (yy_start) )
         (yy_start) = 1;   /* first start state */

      if ( ! yyin )
         yyin = stdin;

      if ( ! yyout )
         yyout = stdout;

      if ( ! YY_CURRENT_BUFFER ) {
         yyensure_buffer_stack ();
         YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
      }

      yy_load_buffer_state( );
      }

   while ( 1 )      /* loops until end-of-file is reached */
      {
      yy_cp = (yy_c_buf_p);

      /* Support of yytext. */
      *yy_cp = (yy_hold_char);

      /* yy_bp points to the position in yy_ch_buf of the start of
       * the current run.
       */
      yy_bp = yy_cp;

      yy_current_state = (yy_start);
yy_match:
      do
         {
         register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
         if ( yy_accept[yy_current_state] )
            {
            (yy_last_accepting_state) = yy_current_state;
            (yy_last_accepting_cpos) = yy_cp;
            }
         while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
            {
            yy_current_state = (int) yy_def[yy_current_state];
            if ( yy_current_state >= 339 )
               yy_c = yy_meta[(unsigned int) yy_c];
            }
         yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
         ++yy_cp;
         }
      while ( yy_base[yy_current_state] != 687 );

yy_find_action:
      yy_act = yy_accept[yy_current_state];
      if ( yy_act == 0 )
         { /* have to back up */
         yy_cp = (yy_last_accepting_cpos);
         yy_current_state = (yy_last_accepting_state);
         yy_act = yy_accept[yy_current_state];
         }

      YY_DO_BEFORE_ACTION;

do_action:   /* This label is used only to access EOF actions. */

      switch ( yy_act )
   { /* beginning of action switch */
         case 0: /* must back up */
         /* undo the effects of YY_DO_BEFORE_ACTION */
         *yy_cp = (yy_hold_char);
         yy_cp = (yy_last_accepting_cpos);
         yy_current_state = (yy_last_accepting_state);
         goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 48 "ADaAn_Lexer.l"
{ comment(); }
   YY_BREAK
case 2:
YY_RULE_SETUP
#line 49 "ADaAn_Lexer.l"
{ /* consume //-comment */ }
   YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 51 "ADaAn_Lexer.l"
{ count(); return ';';}
   YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 52 "ADaAn_Lexer.l"
{ count(); return ';';} 
   YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 53 "ADaAn_Lexer.l"
{ count(); return ';';} 
   YY_BREAK
case 6:
YY_RULE_SETUP
#line 55 "ADaAn_Lexer.l"
{ count();}
   YY_BREAK
case 7:
YY_RULE_SETUP
#line 56 "ADaAn_Lexer.l"
{ count(); return(AUTO); }
   YY_BREAK
case 8:
YY_RULE_SETUP
#line 57 "ADaAn_Lexer.l"
{ count(); return(BOOL); }
   YY_BREAK
case 9:
YY_RULE_SETUP
#line 58 "ADaAn_Lexer.l"
{ count(); return(BREAK); }
   YY_BREAK
case 10:
YY_RULE_SETUP
#line 59 "ADaAn_Lexer.l"
{ count(); return(CASE); }
   YY_BREAK
case 11:
YY_RULE_SETUP
#line 60 "ADaAn_Lexer.l"
{ count(); return(CHAR); }
   YY_BREAK
case 12:
YY_RULE_SETUP
#line 61 "ADaAn_Lexer.l"
{ count(); return(COMPLEX); }
   YY_BREAK
case 13:
YY_RULE_SETUP
#line 62 "ADaAn_Lexer.l"
{ count(); return(CONST); }
   YY_BREAK
case 14:
YY_RULE_SETUP
#line 63 "ADaAn_Lexer.l"
{ count(); return(CONTINUE); }
   YY_BREAK
case 15:
YY_RULE_SETUP
#line 64 "ADaAn_Lexer.l"
{ count(); return(DEFAULT); }
   YY_BREAK
case 16:
YY_RULE_SETUP
#line 65 "ADaAn_Lexer.l"
{ count(); return(DO); }
   YY_BREAK
case 17:
YY_RULE_SETUP
#line 66 "ADaAn_Lexer.l"
{ count(); return(DOUBLE); }
   YY_BREAK
case 18:
YY_RULE_SETUP
#line 67 "ADaAn_Lexer.l"
{ count(); return(ELSE); }
   YY_BREAK
case 19:
YY_RULE_SETUP
#line 68 "ADaAn_Lexer.l"
{ count(); return(ENUM); }
   YY_BREAK
case 20:
YY_RULE_SETUP
#line 69 "ADaAn_Lexer.l"
{ count(); return(EXTERN); }
   YY_BREAK
case 21:
YY_RULE_SETUP
#line 70 "ADaAn_Lexer.l"
{ count(); return(FLOAT); }
   YY_BREAK
case 22:
YY_RULE_SETUP
#line 71 "ADaAn_Lexer.l"
{ count(); return(FOR); }
   YY_BREAK
case 23:
YY_RULE_SETUP
#line 72 "ADaAn_Lexer.l"
{ count(); return(GOTO); }
   YY_BREAK
case 24:
YY_RULE_SETUP
#line 73 "ADaAn_Lexer.l"
{ count(); return(IF); }
   YY_BREAK
case 25:
YY_RULE_SETUP
#line 74 "ADaAn_Lexer.l"
{ count(); return(IMAGINARY); }
   YY_BREAK
case 26:
YY_RULE_SETUP
#line 75 "ADaAn_Lexer.l"
{ count(); return(INLINE); }
   YY_BREAK
case 27:
YY_RULE_SETUP
#line 76 "ADaAn_Lexer.l"
{ count(); return(INT); }
   YY_BREAK
case 28:
YY_RULE_SETUP
#line 77 "ADaAn_Lexer.l"
{ count(); return(LONG); }
   YY_BREAK
case 29:
YY_RULE_SETUP
#line 78 "ADaAn_Lexer.l"
{ count(); return(REGISTER); }
   YY_BREAK
case 30:
YY_RULE_SETUP
#line 79 "ADaAn_Lexer.l"
{ count(); return(RESTRICT); }
   YY_BREAK
case 31:
YY_RULE_SETUP
#line 80 "ADaAn_Lexer.l"
{ count(); return(RESTRICT); }
   YY_BREAK
case 32:
YY_RULE_SETUP
#line 81 "ADaAn_Lexer.l"
{ count(); return(RETURN); }
   YY_BREAK
case 33:
YY_RULE_SETUP
#line 82 "ADaAn_Lexer.l"
{ count(); return(SHORT); }
   YY_BREAK
case 34:
YY_RULE_SETUP
#line 83 "ADaAn_Lexer.l"
{ count(); return(SIGNED); }
   YY_BREAK
case 35:
YY_RULE_SETUP
#line 84 "ADaAn_Lexer.l"
{ count(); return(SIGNED); }
   YY_BREAK
case 36:
YY_RULE_SETUP
#line 85 "ADaAn_Lexer.l"
{ count(); return(SIZEOF); }
   YY_BREAK
case 37:
YY_RULE_SETUP
#line 86 "ADaAn_Lexer.l"
{ count(); return(STATIC); }
   YY_BREAK
case 38:
YY_RULE_SETUP
#line 87 "ADaAn_Lexer.l"
{ count(); return(STRUCT); }
   YY_BREAK
case 39:
YY_RULE_SETUP
#line 88 "ADaAn_Lexer.l"
{ count(); return(SWITCH); }
   YY_BREAK
case 40:
YY_RULE_SETUP
#line 89 "ADaAn_Lexer.l"
{ count(); return(TYPEDEF); }
   YY_BREAK
case 41:
YY_RULE_SETUP
#line 90 "ADaAn_Lexer.l"
{ count(); return(UNION); }
   YY_BREAK
case 42:
YY_RULE_SETUP
#line 91 "ADaAn_Lexer.l"
{ count(); return(UNSIGNED); }
   YY_BREAK
case 43:
YY_RULE_SETUP
#line 92 "ADaAn_Lexer.l"
{ count(); return(VOID); }
   YY_BREAK
case 44:
YY_RULE_SETUP
#line 93 "ADaAn_Lexer.l"
{ count(); return(VOLATILE); }
   YY_BREAK
case 45:
YY_RULE_SETUP
#line 94 "ADaAn_Lexer.l"
{ count(); return(WHILE); }
   YY_BREAK
case 46:
YY_RULE_SETUP
#line 95 "ADaAn_Lexer.l"
{ count(); return(__TRUE); }
   YY_BREAK
case 47:
YY_RULE_SETUP
#line 96 "ADaAn_Lexer.l"
{ count(); return(__FALSE); }
   YY_BREAK
case 48:
YY_RULE_SETUP
#line 98 "ADaAn_Lexer.l"
{ count(); return(check_type()); }
   YY_BREAK
case 49:
YY_RULE_SETUP
#line 100 "ADaAn_Lexer.l"
{ count(); yylval.info.__Value=atoi(yytext);return(CONSTANT); }
   YY_BREAK
case 50:
YY_RULE_SETUP
#line 101 "ADaAn_Lexer.l"
{ count(); yylval.info.__Value=atoi(yytext);return(CONSTANT); }
   YY_BREAK
case 51:
YY_RULE_SETUP
#line 102 "ADaAn_Lexer.l"
{ count(); yylval.info.__Value=atoi(yytext);return(CONSTANT); }
   YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 103 "ADaAn_Lexer.l"
{ count();yylval.info.__Value=yytext[0]; return(CONSTANT); }
   YY_BREAK
case 53:
YY_RULE_SETUP
#line 105 "ADaAn_Lexer.l"
{ count(); yylval.info.__Value=(int)atof(yytext);return(CONSTANT); }
   YY_BREAK
case 54:
YY_RULE_SETUP
#line 106 "ADaAn_Lexer.l"
{ count(); yylval.info.__Value=(int)atof(yytext);return(CONSTANT); }
   YY_BREAK
case 55:
YY_RULE_SETUP
#line 107 "ADaAn_Lexer.l"
{ count(); yylval.info.__Value=(int)atof(yytext);return(CONSTANT); }
   YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 109 "ADaAn_Lexer.l"
{ count(); yylval.info.__Value=(int)yytext[0];/*return(STRING_LITERAL);*/ return CONSTANT; }
   YY_BREAK
case 57:
YY_RULE_SETUP
#line 111 "ADaAn_Lexer.l"
{ count(); return(ELLIPSIS); }
   YY_BREAK
case 58:
YY_RULE_SETUP
#line 112 "ADaAn_Lexer.l"
{ count(); return(RIGHT_ASSIGN); }
   YY_BREAK
case 59:
YY_RULE_SETUP
#line 113 "ADaAn_Lexer.l"
{ count(); return(LEFT_ASSIGN); }
   YY_BREAK
case 60:
YY_RULE_SETUP
#line 114 "ADaAn_Lexer.l"
{ count(); return(ADD_ASSIGN); }
   YY_BREAK
case 61:
YY_RULE_SETUP
#line 115 "ADaAn_Lexer.l"
{ count(); return(SUB_ASSIGN); }
   YY_BREAK
case 62:
YY_RULE_SETUP
#line 116 "ADaAn_Lexer.l"
{ count(); return(MUL_ASSIGN); }
   YY_BREAK
case 63:
YY_RULE_SETUP
#line 117 "ADaAn_Lexer.l"
{ count(); return(DIV_ASSIGN); }
   YY_BREAK
case 64:
YY_RULE_SETUP
#line 118 "ADaAn_Lexer.l"
{ count(); return(MOD_ASSIGN); }
   YY_BREAK
case 65:
YY_RULE_SETUP
#line 119 "ADaAn_Lexer.l"
{ count(); return(AND_ASSIGN); }
   YY_BREAK
case 66:
YY_RULE_SETUP
#line 120 "ADaAn_Lexer.l"
{ count(); return(XOR_ASSIGN); }
   YY_BREAK
case 67:
YY_RULE_SETUP
#line 121 "ADaAn_Lexer.l"
{ count(); return(OR_ASSIGN); }
   YY_BREAK
case 68:
YY_RULE_SETUP
#line 122 "ADaAn_Lexer.l"
{ count(); return(RIGHT_OP); }
   YY_BREAK
case 69:
YY_RULE_SETUP
#line 123 "ADaAn_Lexer.l"
{ count(); return(LEFT_OP); }
   YY_BREAK
case 70:
YY_RULE_SETUP
#line 124 "ADaAn_Lexer.l"
{ count(); return(INC_OP); }
   YY_BREAK
case 71:
YY_RULE_SETUP
#line 125 "ADaAn_Lexer.l"
{ count(); return(DEC_OP); }
   YY_BREAK
case 72:
YY_RULE_SETUP
#line 126 "ADaAn_Lexer.l"
{ count(); return(PTR_OP); }
   YY_BREAK
case 73:
YY_RULE_SETUP
#line 127 "ADaAn_Lexer.l"
{ count(); return(AND_OP); }
   YY_BREAK
case 74:
YY_RULE_SETUP
#line 128 "ADaAn_Lexer.l"
{ count(); return(OR_OP); }
   YY_BREAK
case 75:
YY_RULE_SETUP
#line 129 "ADaAn_Lexer.l"
{ count(); return(LE_OP); }
   YY_BREAK
case 76:
YY_RULE_SETUP
#line 130 "ADaAn_Lexer.l"
{ count(); return(GE_OP); }
   YY_BREAK
case 77:
YY_RULE_SETUP
#line 131 "ADaAn_Lexer.l"
{ count(); return(EQ_OP); }
   YY_BREAK
case 78:
YY_RULE_SETUP
#line 132 "ADaAn_Lexer.l"
{ count(); return(NE_OP); }
   YY_BREAK
case 79:
YY_RULE_SETUP
#line 133 "ADaAn_Lexer.l"
{ count(); return(';'); }
   YY_BREAK
case 80:
YY_RULE_SETUP
#line 134 "ADaAn_Lexer.l"
{ count(); return('{'); }
   YY_BREAK
case 81:
YY_RULE_SETUP
#line 135 "ADaAn_Lexer.l"
{ count(); return('}'); }
   YY_BREAK
case 82:
YY_RULE_SETUP
#line 136 "ADaAn_Lexer.l"
{ count(); return(','); }
   YY_BREAK
case 83:
YY_RULE_SETUP
#line 137 "ADaAn_Lexer.l"
{ count(); return(':'); }
   YY_BREAK
case 84:
YY_RULE_SETUP
#line 138 "ADaAn_Lexer.l"
{ count(); return('='); }
   YY_BREAK
case 85:
YY_RULE_SETUP
#line 139 "ADaAn_Lexer.l"
{ count(); return('('); }
   YY_BREAK
case 86:
YY_RULE_SETUP
#line 140 "ADaAn_Lexer.l"
{ count(); return(')'); }
   YY_BREAK
case 87:
YY_RULE_SETUP
#line 141 "ADaAn_Lexer.l"
{ count(); return('['); }
   YY_BREAK
case 88:
YY_RULE_SETUP
#line 142 "ADaAn_Lexer.l"
{ count(); return(']'); }
   YY_BREAK
case 89:
YY_RULE_SETUP
#line 143 "ADaAn_Lexer.l"
{ count(); return('.'); }
   YY_BREAK
case 90:
YY_RULE_SETUP
#line 144 "ADaAn_Lexer.l"
{ count(); return('&'); }
   YY_BREAK
case 91:
YY_RULE_SETUP
#line 145 "ADaAn_Lexer.l"
{ count(); return('!'); }
   YY_BREAK
case 92:
YY_RULE_SETUP
#line 146 "ADaAn_Lexer.l"
{ count(); return('~'); }
   YY_BREAK
case 93:
YY_RULE_SETUP
#line 147 "ADaAn_Lexer.l"
{ count(); return('-'); }
   YY_BREAK
case 94:
YY_RULE_SETUP
#line 148 "ADaAn_Lexer.l"
{ count(); return('+'); }
   YY_BREAK
case 95:
YY_RULE_SETUP
#line 149 "ADaAn_Lexer.l"
{ count(); return('*'); }
   YY_BREAK
case 96:
YY_RULE_SETUP
#line 150 "ADaAn_Lexer.l"
{ count(); return('/'); }
   YY_BREAK
case 97:
YY_RULE_SETUP
#line 151 "ADaAn_Lexer.l"
{ count(); return('%'); }
   YY_BREAK
case 98:
YY_RULE_SETUP
#line 152 "ADaAn_Lexer.l"
{ count(); return('<'); }
   YY_BREAK
case 99:
YY_RULE_SETUP
#line 153 "ADaAn_Lexer.l"
{ count(); return('>'); }
   YY_BREAK
case 100:
YY_RULE_SETUP
#line 154 "ADaAn_Lexer.l"
{ count(); return('^'); }
   YY_BREAK
case 101:
YY_RULE_SETUP
#line 155 "ADaAn_Lexer.l"
{ count(); return('|'); }
   YY_BREAK
case 102:
YY_RULE_SETUP
#line 156 "ADaAn_Lexer.l"
{ count(); return('?'); }
   YY_BREAK
case 103:
/* rule 103 can match eol */
YY_RULE_SETUP
#line 158 "ADaAn_Lexer.l"
{ count(); }
   YY_BREAK
case 104:
YY_RULE_SETUP
#line 159 "ADaAn_Lexer.l"
{ /* ignore bad characters */ }
   YY_BREAK
case 105:
YY_RULE_SETUP
#line 161 "ADaAn_Lexer.l"
ECHO;
   YY_BREAK
#line 1561 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
   yyterminate();

   case YY_END_OF_BUFFER:
      {
      /* Amount of text matched not including the EOB char. */
      int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

      /* Undo the effects of YY_DO_BEFORE_ACTION. */
      *yy_cp = (yy_hold_char);
      YY_RESTORE_YY_MORE_OFFSET

      if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
         {
         /* We're scanning a new file or input source.  It's
          * possible that this happened because the user
          * just pointed yyin at a new source and called
          * yylex().  If so, then we have to assure
          * consistency between YY_CURRENT_BUFFER and our
          * globals.  Here is the right place to do so, because
          * this is the first action (other than possibly a
          * back-up) that will match for the new input source.
          */
         (yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
         YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
         YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
         }

      /* Note that here we test for yy_c_buf_p "<=" to the position
       * of the first EOB in the buffer, since yy_c_buf_p will
       * already have been incremented past the NUL character
       * (since all states make transitions on EOB to the
       * end-of-buffer state).  Contrast this with the test
       * in input().
       */
      if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
         { /* This was really a NUL. */
         yy_state_type yy_next_state;

         (yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

         yy_current_state = yy_get_previous_state(  );

         /* Okay, we're now positioned to make the NUL
          * transition.  We couldn't have
          * yy_get_previous_state() go ahead and do it
          * for us because it doesn't know how to deal
          * with the possibility of jamming (and we don't
          * want to build jamming into it because then it
          * will run more slowly).
          */

         yy_next_state = yy_try_NUL_trans( yy_current_state );

         yy_bp = (yytext_ptr) + YY_MORE_ADJ;

         if ( yy_next_state )
            {
            /* Consume the NUL. */
            yy_cp = ++(yy_c_buf_p);
            yy_current_state = yy_next_state;
            goto yy_match;
            }

         else
            {
            yy_cp = (yy_c_buf_p);
            goto yy_find_action;
            }
         }

      else switch ( yy_get_next_buffer(  ) )
         {
         case EOB_ACT_END_OF_FILE:
            {
            (yy_did_buffer_switch_on_eof) = 0;

            if ( yywrap( ) )
               {
               /* Note: because we've taken care in
                * yy_get_next_buffer() to have set up
                * yytext, we can now set up
                * yy_c_buf_p so that if some total
                * hoser (like flex itself) wants to
                * call the scanner after we return the
                * YY_NULL, it'll still work - another
                * YY_NULL will get returned.
                */
               (yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

               yy_act = YY_STATE_EOF(YY_START);
               goto do_action;
               }

            else
               {
               if ( ! (yy_did_buffer_switch_on_eof) )
                  YY_NEW_FILE;
               }
            break;
            }

         case EOB_ACT_CONTINUE_SCAN:
            (yy_c_buf_p) =
               (yytext_ptr) + yy_amount_of_matched_text;

            yy_current_state = yy_get_previous_state(  );

            yy_cp = (yy_c_buf_p);
            yy_bp = (yytext_ptr) + YY_MORE_ADJ;
            goto yy_match;

         case EOB_ACT_LAST_MATCH:
            (yy_c_buf_p) =
            &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

            yy_current_state = yy_get_previous_state(  );

            yy_cp = (yy_c_buf_p);
            yy_bp = (yytext_ptr) + YY_MORE_ADJ;
            goto yy_find_action;
         }
      break;
      }

   default:
      YY_FATAL_ERROR(
         "fatal flex scanner internal error--no action found" );
   } /* end of action switch */
      } /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *   EOB_ACT_LAST_MATCH -
 *   EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *   EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
       register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
   register char *source = (yytext_ptr);
   register int number_to_move, i;
   int ret_val;

   if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
      YY_FATAL_ERROR(
      "fatal flex scanner internal error--end of buffer missed" );

   if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
      { /* Don't try to fill the buffer, so this is an EOF. */
      if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
         {
         /* We matched a single character, the EOB, so
          * treat this as a final EOF.
          */
         return EOB_ACT_END_OF_FILE;
         }

      else
         {
         /* We matched some text prior to the EOB, first
          * process it.
          */
         return EOB_ACT_LAST_MATCH;
         }
      }

   /* Try to read more data. */

   /* First move last chars to start of buffer. */
   number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

   for ( i = 0; i < number_to_move; ++i )
      *(dest++) = *(source++);

   if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
      /* don't do the read, it's not guaranteed to return an EOF,
       * just force an EOF
       */
      YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

   else
      {
         int num_to_read =
         YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

      while ( num_to_read <= 0 )
         { /* Not enough room in the buffer - grow it. */

         /* just a shorter name for the current buffer */
         YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

         int yy_c_buf_p_offset =
            (int) ((yy_c_buf_p) - b->yy_ch_buf);

         if ( b->yy_is_our_buffer )
            {
            int new_size = b->yy_buf_size * 2;

            if ( new_size <= 0 )
               b->yy_buf_size += b->yy_buf_size / 8;
            else
               b->yy_buf_size *= 2;

            b->yy_ch_buf = (char *)
               /* Include room in for 2 EOB chars. */
               yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
            }
         else
            /* Can't grow it, we don't own it. */
            b->yy_ch_buf = 0;

         if ( ! b->yy_ch_buf )
            YY_FATAL_ERROR(
            "fatal error - scanner input buffer overflow" );

         (yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

         num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
                  number_to_move - 1;

         }

      if ( num_to_read > YY_READ_BUF_SIZE )
         num_to_read = YY_READ_BUF_SIZE;

      /* Read in more data. */
      YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
         (yy_n_chars), (size_t) num_to_read );

      YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
      }

   if ( (yy_n_chars) == 0 )
      {
      if ( number_to_move == YY_MORE_ADJ )
         {
         ret_val = EOB_ACT_END_OF_FILE;
         yyrestart(yyin  );
         }

      else
         {
         ret_val = EOB_ACT_LAST_MATCH;
         YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
            YY_BUFFER_EOF_PENDING;
         }
      }

   else
      ret_val = EOB_ACT_CONTINUE_SCAN;

   if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
      /* Extend the array by 50%, plus the number we really need. */
      yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
      YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
      if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
         YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
   }

   (yy_n_chars) += number_to_move;
   YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
   YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

   (yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

   return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
   register yy_state_type yy_current_state;
   register char *yy_cp;
    
   yy_current_state = (yy_start);

   for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
      {
      register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
      if ( yy_accept[yy_current_state] )
         {
         (yy_last_accepting_state) = yy_current_state;
         (yy_last_accepting_cpos) = yy_cp;
         }
      while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
         {
         yy_current_state = (int) yy_def[yy_current_state];
         if ( yy_current_state >= 339 )
            yy_c = yy_meta[(unsigned int) yy_c];
         }
      yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
      }

   return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *   next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
   register int yy_is_jam;
       register char *yy_cp = (yy_c_buf_p);

   register YY_CHAR yy_c = 1;
   if ( yy_accept[yy_current_state] )
      {
      (yy_last_accepting_state) = yy_current_state;
      (yy_last_accepting_cpos) = yy_cp;
      }
   while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
      {
      yy_current_state = (int) yy_def[yy_current_state];
      if ( yy_current_state >= 339 )
         yy_c = yy_meta[(unsigned int) yy_c];
      }
   yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
   yy_is_jam = (yy_current_state == 338);

   return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
   register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

   /* undo effects of setting up yytext */
   *yy_cp = (yy_hold_char);

   if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
      { /* need to shift things up to make room */
      /* +2 for EOB chars. */
      register int number_to_move = (yy_n_chars) + 2;
      register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
               YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
      register char *source =
            &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

      while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
         *--dest = *--source;

      yy_cp += (int) (dest - source);
      yy_bp += (int) (dest - source);
      YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
         (yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

      if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
         YY_FATAL_ERROR( "flex scanner push-back overflow" );
      }

   *--yy_cp = (char) c;

   (yytext_ptr) = yy_bp;
   (yy_hold_char) = *yy_cp;
   (yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
   int c;
    
   *(yy_c_buf_p) = (yy_hold_char);

   if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
      {
      /* yy_c_buf_p now points to the character we want to return.
       * If this occurs *before* the EOB characters, then it's a
       * valid NUL; if not, then we've hit the end of the buffer.
       */
      if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
         /* This was really a NUL. */
         *(yy_c_buf_p) = '\0';

      else
         { /* need more input */
         int offset = (yy_c_buf_p) - (yytext_ptr);
         ++(yy_c_buf_p);

         switch ( yy_get_next_buffer(  ) )
            {
            case EOB_ACT_LAST_MATCH:
               /* This happens because yy_g_n_b()
                * sees that we've accumulated a
                * token and flags that we need to
                * try matching the token before
                * proceeding.  But for input(),
                * there's no matching to consider.
                * So convert the EOB_ACT_LAST_MATCH
                * to EOB_ACT_END_OF_FILE.
                */

               /* Reset buffer status. */
               yyrestart(yyin );

               /*FALLTHROUGH*/

            case EOB_ACT_END_OF_FILE:
               {
               if ( yywrap( ) )
                  return EOF;

               if ( ! (yy_did_buffer_switch_on_eof) )
                  YY_NEW_FILE;
#ifdef __cplusplus
               return yyinput();
#else
               return input();
#endif
               }

            case EOB_ACT_CONTINUE_SCAN:
               (yy_c_buf_p) = (yytext_ptr) + offset;
               break;
            }
         }
      }

   c = *(unsigned char *) (yy_c_buf_p);   /* cast for 8-bit char's */
   *(yy_c_buf_p) = '\0';   /* preserve yytext */
   (yy_hold_char) = *++(yy_c_buf_p);

   return c;
}
#endif   /* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
   if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
      YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
   }

   yy_init_buffer(YY_CURRENT_BUFFER,input_file );
   yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
   /* TODO. We should be able to replace this entire function body
    * with
    *      yypop_buffer_state();
    *      yypush_buffer_state(new_buffer);
     */
   yyensure_buffer_stack ();
   if ( YY_CURRENT_BUFFER == new_buffer )
      return;

   if ( YY_CURRENT_BUFFER )
      {
      /* Flush out information for old buffer. */
      *(yy_c_buf_p) = (yy_hold_char);
      YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
      YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
      }

   YY_CURRENT_BUFFER_LVALUE = new_buffer;
   yy_load_buffer_state( );

   /* We don't actually know whether we did this switch during
    * EOF (yywrap()) processing, but the only time this flag
    * is looked at is after yywrap() is called, so it's safe
    * to go ahead and always set it.
    */
   (yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
       (yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
   (yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
   yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
   (yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
   YY_BUFFER_STATE b;
    
   b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
   if ( ! b )
      YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

   b->yy_buf_size = size;

   /* yy_ch_buf has to be 2 characters longer than the size given because
    * we need to put in 2 end-of-buffer characters.
    */
   b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
   if ( ! b->yy_ch_buf )
      YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

   b->yy_is_our_buffer = 1;

   yy_init_buffer(b,file );

   return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
   if ( ! b )
      return;

   if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
      YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

   if ( b->yy_is_our_buffer )
      yyfree((void *) b->yy_ch_buf  );

   yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
   int oerrno = errno;
    
   yy_flush_buffer(b );

   b->yy_input_file = file;
   b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
   errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
       if ( ! b )
      return;

   b->yy_n_chars = 0;

   /* We always need two end-of-buffer characters.  The first causes
    * a transition to the end-of-buffer state.  The second causes
    * a jam in that state.
    */
   b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
   b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

   b->yy_buf_pos = &b->yy_ch_buf[0];

   b->yy_at_bol = 1;
   b->yy_buffer_status = YY_BUFFER_NEW;

   if ( b == YY_CURRENT_BUFFER )
      yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
       if (new_buffer == NULL)
      return;

   yyensure_buffer_stack();

   /* This block is copied from yy_switch_to_buffer. */
   if ( YY_CURRENT_BUFFER )
      {
      /* Flush out information for old buffer. */
      *(yy_c_buf_p) = (yy_hold_char);
      YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
      YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
      }

   /* Only push if top exists. Otherwise, replace top. */
   if (YY_CURRENT_BUFFER)
      (yy_buffer_stack_top)++;
   YY_CURRENT_BUFFER_LVALUE = new_buffer;

   /* copied from yy_switch_to_buffer. */
   yy_load_buffer_state( );
   (yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
       if (!YY_CURRENT_BUFFER)
      return;

   yy_delete_buffer(YY_CURRENT_BUFFER );
   YY_CURRENT_BUFFER_LVALUE = NULL;
   if ((yy_buffer_stack_top) > 0)
      --(yy_buffer_stack_top);

   if (YY_CURRENT_BUFFER) {
      yy_load_buffer_state( );
      (yy_did_buffer_switch_on_eof) = 1;
   }
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
   int num_to_alloc;
    
   if (!(yy_buffer_stack)) {

      /* First allocation is just for 2 elements, since we don't know if this
       * scanner will even need a stack. We use 2 instead of 1 to avoid an
       * immediate realloc on the next call.
         */
      num_to_alloc = 1;
      (yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
                        (num_to_alloc * sizeof(struct yy_buffer_state*)
                        );
      if ( ! (yy_buffer_stack) )
         YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
                          
      memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
            
      (yy_buffer_stack_max) = num_to_alloc;
      (yy_buffer_stack_top) = 0;
      return;
   }

   if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

      /* Increase the buffer to prepare for a possible push. */
      int grow_size = 8 /* arbitrary grow size */;

      num_to_alloc = (yy_buffer_stack_max) + grow_size;
      (yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
                        ((yy_buffer_stack),
                        num_to_alloc * sizeof(struct yy_buffer_state*)
                        );
      if ( ! (yy_buffer_stack) )
         YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

      /* zero only the new slots.*/
      memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
      (yy_buffer_stack_max) = num_to_alloc;
   }
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
   YY_BUFFER_STATE b;
    
   if ( size < 2 ||
        base[size-2] != YY_END_OF_BUFFER_CHAR ||
        base[size-1] != YY_END_OF_BUFFER_CHAR )
      /* They forgot to leave room for the EOB's. */
      return 0;

   b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
   if ( ! b )
      YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

   b->yy_buf_size = size - 2;   /* "- 2" to take care of EOB's */
   b->yy_buf_pos = b->yy_ch_buf = base;
   b->yy_is_our_buffer = 0;
   b->yy_input_file = 0;
   b->yy_n_chars = b->yy_buf_size;
   b->yy_is_interactive = 0;
   b->yy_at_bol = 1;
   b->yy_fill_buffer = 0;
   b->yy_buffer_status = YY_BUFFER_NEW;

   yy_switch_to_buffer(b  );

   return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
   return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
   YY_BUFFER_STATE b;
   char *buf;
   yy_size_t n;
   int i;
    
   /* Get memory for full buffer, including space for trailing EOB's. */
   n = _yybytes_len + 2;
   buf = (char *) yyalloc(n  );
   if ( ! buf )
      YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

   for ( i = 0; i < _yybytes_len; ++i )
      buf[i] = yybytes[i];

   buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

   b = yy_scan_buffer(buf,n );
   if ( ! b )
      YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

   /* It's okay to grow etc. this buffer, and we should throw it
    * away when we're done.
    */
   b->yy_is_our_buffer = 1;

   return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
       (void) fprintf( stderr, "%s\n", msg );
   exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
   do \
      { \
      /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
      yytext[yyleng] = (yy_hold_char); \
      (yy_c_buf_p) = yytext + yyless_macro_arg; \
      (yy_hold_char) = *(yy_c_buf_p); \
      *(yy_c_buf_p) = '\0'; \
      yyleng = yyless_macro_arg; \
      } \
   while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
   while(YY_CURRENT_BUFFER){
      yy_delete_buffer(YY_CURRENT_BUFFER  );
      YY_CURRENT_BUFFER_LVALUE = NULL;
      yypop_buffer_state();
   }

   /* Destroy the stack itself. */
   yyfree((yy_buffer_stack) );
   (yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
   register int i;
   for ( i = 0; i < n; ++i )
      s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
   register int n;
   for ( n = 0; s[n]; ++n )
      ;

   return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
   return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
   /* The cast to (char *) in the following accommodates both
    * implementations that use char* generic pointers, and those
    * that use void* generic pointers.  It works with the latter
    * because both ANSI C and C++ allow castless assignment from
    * any pointer type to void*, and deal with argument conversions
    * as though doing an assignment.
    */
   return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
   free( (char *) ptr );   /* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 161 "ADaAn_Lexer.l"



yywrap()
{
   return(1);
}


comment()
{
   char c, prev = 0;
  
   while ((c = input()) != 0)      /* (EOF maps to 0) */
   {
      if (c == '/' && prev == '*')
         return;
      prev = c;
   }
   error("unterminated comment");
}


int column = 0;

void count()
{
   int i;
   parser_col+=yyleng;
   for (i = 0; yytext[i] != '\0'; i++)
      if (yytext[i] == '\n'){
         column = 0;
         parser_line++;
         parser_col=0;
         }
      else if (yytext[i] == '\t')
         column += 8 - (column % 8);
      else
         column++;

//   ECHO;
  
}




int check_type()
{

   strcpy(yylval.info.__ID,yytext);
   if((*fct)(yytext))
            return(TYPE_NAME);
   else
      return(IDENTIFIER);
}



